### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [Z-Wave-Me/zwave-me-ws#1]
Could you please tag the source again? Otherwise all distributions which were shipping this Python module and were using the GitHub releases need to change their description to build the packages.

Thanks

**Comment by PoltoS** [comment]
Sorry, could you be more specific, please? We have tags on each release.

**Comment by fabaff** [comment]
I guess 0.3.5 was a glitch as this was only available on PyPI.

**Comment by PoltoS** [comment]
Ah, indeed, 0.3.5 was missing here on GitHub. Now I got you. Thanks for pointing out
